### ISSUE TITLE
Beta number 2 is out!

### ISSUE THREAD

**Issue by remotevase** [MineCode-Devs/DevMine#2]
Hey guys! 
Hooray! Beta number 2 is out! 
Unfortunately, we have yet another problem: nothing. Yes, the problem name is "**nothing**". 
What this means is that
1. When the server starts, all of the folders (crashdumps, worlds, players, plugins) generate
2. The worlds do not generate
3. Nothing shows up in console
4. Nothing shows up in MCPE (Meaning there is no sign of the server being on)
5. The Devmine.yml, Devmine2.yml and setup wizard do not show up. Then, when I added Devmine.yml, Devmine2.yml and server.properties, nothing showed up then in console either! I tried fixing many ways, nothing worked. Who can help?

**Comment by remotevase** [comment]
I believe it will be some sort of problem with the logger files? Maybe?

**Comment by Super35** [comment]
@remotevase is there a Exe for DevMine ?

**Comment by Super35** [comment]
remotevase commented 3 days ago
DA hell! I thought I added you! Anyways, the org name will be changed to DM Corporation AKA DM Corp

This what u said why didnt change name of org

**Comment by remotevase** [comment]
Naw, I thought twice about that decision

**Comment by Super35** [comment]
Ok

**Comment by dragonwocky** [comment]
Soo... If this wasn't happening in Beta #1..... Maybe when you changed something to fix the bug in #1, it created the bug in #2? (Or am I just confused again?)

**Comment by remotevase** [comment]
I don't even know anymore... Just someone please fix and upload new beta. I cannot figure it out...
@Ad5001 @PHP Proffesor (AKA @Taki21) @AmiroEmad @Keithkfng

**Comment by Ad5001** [comment]
Too much things to do rn , sorry...

**Comment by dragonwocky** [comment]
I'll have a look at src code after school if I get time....

**Comment by remotevase** [comment]
Thanks @TheDragonRing
@Ad5001 I bet that you are just working on plugins

**Comment by remotevase** [comment]
Thanks @TheDragonRing
@Ad5001 I bet that you are just working on plugins jk, kidding, I get dose days too

**Comment by Ad5001** [comment]
Yeah, I work on finishing big plugins :,) the community wants them x)

**Comment by Super35** [comment]
Plugins will be on @Ad5001 ?

Will pocketmine plugins work ?

**Comment by Ad5001** [comment]
As @remotevase said, no.

**Comment by Super35** [comment]
Means that DevMine will have its own Plugin ?

**Comment by MiroTheSuperDev** [comment]
dev mine is for devs devs make their plugins for dev mine the end

**Comment by MiroTheSuperDev** [comment]
dev = developer

**Comment by Super35** [comment]
Means we make plugins ? For Those Using DevMine

**Comment by remotevase** [comment]
@TheProest35YT yes, once we are able to get a stable server, I will implement a bunch of plugins into the DevMine/pluginfeatures folder. In addition, we can all convert plugins from PM to DM by using  the conversions in the README

**Comment by Sandertv** [comment]
I'd really like to learn about software code but right now I can't do a lot... I'm willing to learn though.

**Comment by MiroTheSuperDev** [comment]
i think we really should start from the begining not using zips but uploading files to the github and start doing it remote vase copy and paste files using github desktop clone and i will change the code to the files

**Comment by Taki21** [comment]
ya its getting crazy @remotevase

**Comment by MiroTheSuperDev** [comment]
if anyone agree with my previous reply type in chat +1 or :+1:

**Comment by remotevase** [comment]
Yes, @AmiroEmad I shall do that tomorrow surely!

**Comment by TheProest35YT** [comment]
Should we make a group for DevMinePlugins

If u want i invited you all

@DMPlugins

**Comment by dragonwocky** [comment]
@TheProest35YT First we need to get DevMine working.

**Comment by Sandertv** [comment]
I'd like to help but I still have to learn about softwares

**Comment by k3ithos** [comment]
Can we stop making more server software? 5 is already enough, with 2 of them just being a fork. Just contribute to PocketMine.

**Comment by MiroTheSuperDev** [comment]
dear @keithkfng 

1- pocketmine doesnt even look in their pull request

2- this software is not a whole new fork its just make it more organized and easier for developers .

3- all credits are still applied to pocketmine we just changed file format

**Comment by TheProest35YT** [comment]
Dear Mr @keithkfng 

This Software (DevMine))

Does not Use
PM code base

They changed codes 

Go to the readme.md to check the code changes

**Comment by k3ithos** [comment]
For the last time, they did not change code base. This shows that you have not understood what they have done correctly. They only changed the **_folder & file structure_**. Instead of pocketmine\utils, it becomes devmine\utils. That doesn't change the code within the files at all. It only changes where **_file is situated_**. They also created extra directories where old files from the PocketMine code base sit now.<br>
To be honest, if I was the owner of this project I would scrap it. You've changed so much - and at this point, it doesn't look like anybody is going to go to the degree of editing their plugins folder structure, blah blah blah just to make it compatible with DevMine. You see, the reason people like ClearSky, Genisys, etc. is because they're better than PocketMine - but they're also forked from it, hence PocketMine plugins still work without modification and extra work. Other users don't have to bother them everytime and just drag and drop the plugins without any complicated way involved.
Just my opinion, but I hope it changes your mind.

**Comment by MiroTheSuperDev** [comment]
@keithkfng ok i think your right but all remote_vase meant is to make files in pocketmine more organized but i think it might be harder to people to re learn 

i just realized everyone think genisys and clearsky are forks but in real they are clones

**Comment by Taki21** [comment]
@TheProest35YT why are u so concerned what this repo did so different?
Please read the license and the readme properly 

@Keith I agree there at lots of mine software but know that I think of it ... if they want to work on it let them ... eventually we will fade away from the mine software and work on something new.

**Comment by Taki21** [comment]
I know u want to create ur own mine software why don't we just start from scratch? I'll give an example as an idea: see the bukkit servers 4 MC PC have no bugs.why? Because they used the "same" code differently and also it's java like the MC app

Also  u see how people can connect without the server?  It's a pure local world but with some code who knows what u can do. One day we will realize that duplicating something from the dead is just a waste of time and energy

**Comment by MiroTheSuperDev** [comment]
the owner of pocketmine even no longer cares about it and he told iamapond that he will never come back 

but @Taki21 doing a new mcpe software is always a great idea but the problem is always with the protocols how to get them how to code them how to use them how to make them work with the script it self 

there is also new mcpe server software by itxtech its called cenysis a server software written in c++

**Comment by Taki21** [comment]
I know how to get the protocols

**Comment by remotevase** [comment]
Btw can someone upload the betas to gH? I gh desktop didn't work for me. Please upload the correct beta zips to the correct beta branch? See the branches page for details. Also, after uploading B2 zip, please make a new branch off of the B2 branch named B3 so we can edit B2 in order to complete B3

**Comment by remotevase** [comment]
Oh @AmiroEmad why did you delete the beta zips? At least keep B1, because B1 was where all the folder renaming was done in file (in statements... Etc) AND in folders itself. That is the first step no matter what we do, so at LEAST keep B1 and follow the instructions above.

Also, @TheProest35YT why do you care so much about me? Just because I started this project doesn't mean that everybody else is irrelevant! Example: instead of starting issue called "so do we need an exe", instead, you start an issue that is ONLY to me! Called "so **remote**..." Which means that you think that I am the only decision maker... There are many other instances of this

**Comment by Super35** [comment]
Some of the codes are just added with s and changed to DevMine

1 Example
pocketmine\event --> devmine\events

**Comment by remotevase** [comment]
Yes, because the purpose of DM is for organization, and events gets its own category

**Comment by Super35** [comment]
Sure ! I get it now

**Comment by Sandertv** [comment]
I agree with Taki, but I honestly don't think the development team here is big enough to write a whole new server software...

**Comment by Super35** [comment]
@Sandertv  I Also Agree with @Taki21 & You and I Also Wanna Say we need at least 8 , 9 , 10 Genius To Make A Good Software and there will be maybe only a little bugs only

**Comment by Taki21** [comment]
@AmiroEmad when u say Genisys is making Cenisys its not suprising at all, all their doing is the same project as pocketmine **Translated** into C++ they arent starting from scratch but really making a replica in a different coding language. If they didnt have pocketmine they coudln't do Cenisys.

Also, My idea of using a local world to make it a server, heres some stuff i should tell you:
I port forwarded my server but now i dont use or even have one, its deleted, but my minecraft server has been port forwarded (pf) so in general i port forwarded and the result of this is: When people put playsw.tk: 19132 in the add server screen, and when i am playing in my local world, they join my LOCAL WORLD!!! Its a server?! 

Now think. There is also realms too, we can use a similar method to realms because its on even though the owners away. With some coding we can make mods or "plugins"! 

Think about these ideas as i snack on a bag of takis :p

**Comment by Super35** [comment]
Cenisys is Made with Java not C++

**Comment by Super35** [comment]
Cenisys is a fork of the Nukkit Project

**Comment by Taki21** [comment]
No it's not clearly. u don't know what java  is

**Comment by Super35** [comment]
Ok

**Comment by Taki21** [comment]
.cpp means c++ .java means java

**Comment by Super35** [comment]
MiNet is C#

**Comment by Super35** [comment]
Gurun's MiNet

**Comment by keithkfng** [comment]
See? Why would you even attempt to try and make ProestMine if you can't even point out if the project is written using C#, C++ and Java. MiNET is written using C#. You don't even need to look at the source code - it already tells you in the repository description and the README.

**Comment by Super35** [comment]
Ok so I made a mistake

**Comment by TheProest35YT** [comment]
P'S: ProestMine is Deleted

**Comment by MiroTheSuperDev** [comment]
so guys what are we going to do here with devmine

**Comment by remotevase** [comment]
Somebody upload it from B1 (I cant upload, gh-desktop not work for me). I just re-uploaded the beta builds, so somebody do this

> Please upload the correct beta zips to the correct beta branch? See the branches page for details. Also, after uploading B1 zip, please make a new branch off of the B1 branch named B2 so we can edit B1 in order to complete B2 inside of the B2 branch

**Comment by remotevase** [comment]
Also, @AmiroEmad in B1, nothing was done except for re-arrange the files, and replace all instances of the old file path with the new file path

**Comment by remotevase** [comment]
Therefore, if we use B1, it is just like starting from scratch because B1 would be the first step to doing this NO MATTER how we do it.

**Comment by MiroTheSuperDev** [comment]
ok i will start working when i finish server manager

**Comment by remotevase** [comment]
@AmiroEmad will that be sometime in the next week please? Also, B2 is no longer out. Now B1. New issue called "chat"

**Comment by Super35** [comment]
Lock issue for no spam
